apiVersion: v1
kind: Pod
metadata:
  name: multi-container-app
spec:
  volumes:
    - name: logs
      emptyDir: {}

  initContainers:
    - name: init-container
      image: busybox
      command: ['sh', '-c', 'echo "Hello from Init Container" > /shared/log.log']
      volumeMounts:
        - name: logs
          mountPath: /shared

  containers:
    - name: nginx
      image: nginx-multicontainer-app:1.0.0
      ports:
        - containerPort: 80
      volumeMounts:
        - name: logs
          mountPath: /var/log/nginx

    - name: log-tailer
      image: busybox
      command: ['sh', '-c', 'tail -f /var/log/nginx/access.log']
      volumeMounts:
        - name: logs
          mountPath: /var/log/nginx
